/// Revelation place of a Surah.
enum RevelationType { meccan, medinan }

extension RevelationTypeLabel on RevelationType {
  String get label => this == RevelationType.meccan ? 'Meccan' : 'Medinan';
}

/// A single Surah entry for the Surah List screen.
class SurahInfo {
  final int number;
  final String englishName;
  final String arabicName;
  final RevelationType revelationType;
  final int ayahCount;

  const SurahInfo({
    required this.number,
    required this.englishName,
    required this.arabicName,
    required this.revelationType,
    required this.ayahCount,
  });

  String get numberLabel => number.toString().padLeft(2, '0');
  String get metaLabel => '${revelationType.label} • $ayahCount Ayahs';
}

const RevelationType _m = RevelationType.meccan;
const RevelationType _d = RevelationType.medinan;

/// All 114 Surahs of the Quran with standard English/Arabic names,
/// revelation type, and ayah counts. Reference data — used for UI mock
/// purposes only, no Quranic text is reproduced.
const List<SurahInfo> allSurahs = [
  SurahInfo(
    number: 1,
    englishName: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    revelationType: _m,
    ayahCount: 7,
  ),
  SurahInfo(
    number: 2,
    englishName: 'Al-Baqarah',
    arabicName: 'البقرة',
    revelationType: _d,
    ayahCount: 286,
  ),
  SurahInfo(
    number: 3,
    englishName: "Aal-E-Imran",
    arabicName: 'آل عمران',
    revelationType: _d,
    ayahCount: 200,
  ),
  SurahInfo(
    number: 4,
    englishName: 'An-Nisa',
    arabicName: 'النساء',
    revelationType: _d,
    ayahCount: 176,
  ),
  SurahInfo(
    number: 5,
    englishName: "Al-Ma'idah",
    arabicName: 'المائدة',
    revelationType: _d,
    ayahCount: 120,
  ),
  SurahInfo(
    number: 6,
    englishName: "Al-An'am",
    arabicName: 'الأنعام',
    revelationType: _m,
    ayahCount: 165,
  ),
  SurahInfo(
    number: 7,
    englishName: "Al-A'raf",
    arabicName: 'الأعراف',
    revelationType: _m,
    ayahCount: 206,
  ),
  SurahInfo(
    number: 8,
    englishName: 'Al-Anfal',
    arabicName: 'الأنفال',
    revelationType: _d,
    ayahCount: 75,
  ),
  SurahInfo(
    number: 9,
    englishName: 'At-Tawbah',
    arabicName: 'التوبة',
    revelationType: _d,
    ayahCount: 129,
  ),
  SurahInfo(
    number: 10,
    englishName: 'Yunus',
    arabicName: 'يونس',
    revelationType: _m,
    ayahCount: 109,
  ),
  SurahInfo(
    number: 11,
    englishName: 'Hud',
    arabicName: 'هود',
    revelationType: _m,
    ayahCount: 123,
  ),
  SurahInfo(
    number: 12,
    englishName: 'Yusuf',
    arabicName: 'يوسف',
    revelationType: _m,
    ayahCount: 111,
  ),
  SurahInfo(
    number: 13,
    englishName: "Ar-Ra'd",
    arabicName: 'الرعد',
    revelationType: _d,
    ayahCount: 43,
  ),
  SurahInfo(
    number: 14,
    englishName: 'Ibrahim',
    arabicName: 'إبراهيم',
    revelationType: _m,
    ayahCount: 52,
  ),
  SurahInfo(
    number: 15,
    englishName: 'Al-Hijr',
    arabicName: 'الحجر',
    revelationType: _m,
    ayahCount: 99,
  ),
  SurahInfo(
    number: 16,
    englishName: 'An-Nahl',
    arabicName: 'النحل',
    revelationType: _m,
    ayahCount: 128,
  ),
  SurahInfo(
    number: 17,
    englishName: 'Al-Isra',
    arabicName: 'الإسراء',
    revelationType: _m,
    ayahCount: 111,
  ),
  SurahInfo(
    number: 18,
    englishName: 'Al-Kahf',
    arabicName: 'الكهف',
    revelationType: _m,
    ayahCount: 110,
  ),
  SurahInfo(
    number: 19,
    englishName: 'Maryam',
    arabicName: 'مريم',
    revelationType: _m,
    ayahCount: 98,
  ),
  SurahInfo(
    number: 20,
    englishName: 'Ta-Ha',
    arabicName: 'طه',
    revelationType: _m,
    ayahCount: 135,
  ),
  SurahInfo(
    number: 21,
    englishName: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    revelationType: _m,
    ayahCount: 112,
  ),
  SurahInfo(
    number: 22,
    englishName: 'Al-Hajj',
    arabicName: 'الحج',
    revelationType: _d,
    ayahCount: 78,
  ),
  SurahInfo(
    number: 23,
    englishName: "Al-Mu'minun",
    arabicName: 'المؤمنون',
    revelationType: _m,
    ayahCount: 118,
  ),
  SurahInfo(
    number: 24,
    englishName: 'An-Nur',
    arabicName: 'النور',
    revelationType: _d,
    ayahCount: 64,
  ),
  SurahInfo(
    number: 25,
    englishName: 'Al-Furqan',
    arabicName: 'الفرقان',
    revelationType: _m,
    ayahCount: 77,
  ),
  SurahInfo(
    number: 26,
    englishName: "Ash-Shu'ara",
    arabicName: 'الشعراء',
    revelationType: _m,
    ayahCount: 227,
  ),
  SurahInfo(
    number: 27,
    englishName: 'An-Naml',
    arabicName: 'النمل',
    revelationType: _m,
    ayahCount: 93,
  ),
  SurahInfo(
    number: 28,
    englishName: 'Al-Qasas',
    arabicName: 'القصص',
    revelationType: _m,
    ayahCount: 88,
  ),
  SurahInfo(
    number: 29,
    englishName: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    revelationType: _m,
    ayahCount: 69,
  ),
  SurahInfo(
    number: 30,
    englishName: 'Ar-Rum',
    arabicName: 'الروم',
    revelationType: _m,
    ayahCount: 60,
  ),
  SurahInfo(
    number: 31,
    englishName: 'Luqman',
    arabicName: 'لقمان',
    revelationType: _m,
    ayahCount: 34,
  ),
  SurahInfo(
    number: 32,
    englishName: 'As-Sajdah',
    arabicName: 'السجدة',
    revelationType: _m,
    ayahCount: 30,
  ),
  SurahInfo(
    number: 33,
    englishName: 'Al-Ahzab',
    arabicName: 'الأحزاب',
    revelationType: _d,
    ayahCount: 73,
  ),
  SurahInfo(
    number: 34,
    englishName: 'Saba',
    arabicName: 'سبأ',
    revelationType: _m,
    ayahCount: 54,
  ),
  SurahInfo(
    number: 35,
    englishName: 'Fatir',
    arabicName: 'فاطر',
    revelationType: _m,
    ayahCount: 45,
  ),
  SurahInfo(
    number: 36,
    englishName: 'Ya-Sin',
    arabicName: 'يس',
    revelationType: _m,
    ayahCount: 83,
  ),
  SurahInfo(
    number: 37,
    englishName: 'As-Saffat',
    arabicName: 'الصافات',
    revelationType: _m,
    ayahCount: 182,
  ),
  SurahInfo(
    number: 38,
    englishName: 'Sad',
    arabicName: 'ص',
    revelationType: _m,
    ayahCount: 88,
  ),
  SurahInfo(
    number: 39,
    englishName: 'Az-Zumar',
    arabicName: 'الزمر',
    revelationType: _m,
    ayahCount: 75,
  ),
  SurahInfo(
    number: 40,
    englishName: 'Ghafir',
    arabicName: 'غافر',
    revelationType: _m,
    ayahCount: 85,
  ),
  SurahInfo(
    number: 41,
    englishName: 'Fussilat',
    arabicName: 'فصلت',
    revelationType: _m,
    ayahCount: 54,
  ),
  SurahInfo(
    number: 42,
    englishName: 'Ash-Shuraa',
    arabicName: 'الشورى',
    revelationType: _m,
    ayahCount: 53,
  ),
  SurahInfo(
    number: 43,
    englishName: 'Az-Zukhruf',
    arabicName: 'الزخرف',
    revelationType: _m,
    ayahCount: 89,
  ),
  SurahInfo(
    number: 44,
    englishName: 'Ad-Dukhan',
    arabicName: 'الدخان',
    revelationType: _m,
    ayahCount: 59,
  ),
  SurahInfo(
    number: 45,
    englishName: 'Al-Jathiyah',
    arabicName: 'الجاثية',
    revelationType: _m,
    ayahCount: 37,
  ),
  SurahInfo(
    number: 46,
    englishName: 'Al-Ahqaf',
    arabicName: 'الأحقاف',
    revelationType: _m,
    ayahCount: 35,
  ),
  SurahInfo(
    number: 47,
    englishName: 'Muhammad',
    arabicName: 'محمد',
    revelationType: _d,
    ayahCount: 38,
  ),
  SurahInfo(
    number: 48,
    englishName: 'Al-Fath',
    arabicName: 'الفتح',
    revelationType: _d,
    ayahCount: 29,
  ),
  SurahInfo(
    number: 49,
    englishName: 'Al-Hujurat',
    arabicName: 'الحجرات',
    revelationType: _d,
    ayahCount: 18,
  ),
  SurahInfo(
    number: 50,
    englishName: 'Qaf',
    arabicName: 'ق',
    revelationType: _m,
    ayahCount: 45,
  ),
  SurahInfo(
    number: 51,
    englishName: 'Adh-Dhariyat',
    arabicName: 'الذاريات',
    revelationType: _m,
    ayahCount: 60,
  ),
  SurahInfo(
    number: 52,
    englishName: 'At-Tur',
    arabicName: 'الطور',
    revelationType: _m,
    ayahCount: 49,
  ),
  SurahInfo(
    number: 53,
    englishName: 'An-Najm',
    arabicName: 'النجم',
    revelationType: _m,
    ayahCount: 62,
  ),
  SurahInfo(
    number: 54,
    englishName: 'Al-Qamar',
    arabicName: 'القمر',
    revelationType: _m,
    ayahCount: 55,
  ),
  SurahInfo(
    number: 55,
    englishName: 'Ar-Rahman',
    arabicName: 'الرحمن',
    revelationType: _d,
    ayahCount: 78,
  ),
  SurahInfo(
    number: 56,
    englishName: "Al-Waqi'ah",
    arabicName: 'الواقعة',
    revelationType: _m,
    ayahCount: 96,
  ),
  SurahInfo(
    number: 57,
    englishName: 'Al-Hadid',
    arabicName: 'الحديد',
    revelationType: _d,
    ayahCount: 29,
  ),
  SurahInfo(
    number: 58,
    englishName: 'Al-Mujadila',
    arabicName: 'المجادلة',
    revelationType: _d,
    ayahCount: 22,
  ),
  SurahInfo(
    number: 59,
    englishName: 'Al-Hashr',
    arabicName: 'الحشر',
    revelationType: _d,
    ayahCount: 24,
  ),
  SurahInfo(
    number: 60,
    englishName: 'Al-Mumtahanah',
    arabicName: 'الممتحنة',
    revelationType: _d,
    ayahCount: 13,
  ),
  SurahInfo(
    number: 61,
    englishName: 'As-Saff',
    arabicName: 'الصف',
    revelationType: _d,
    ayahCount: 14,
  ),
  SurahInfo(
    number: 62,
    englishName: "Al-Jumu'ah",
    arabicName: 'الجمعة',
    revelationType: _d,
    ayahCount: 11,
  ),
  SurahInfo(
    number: 63,
    englishName: 'Al-Munafiqun',
    arabicName: 'المنافقون',
    revelationType: _d,
    ayahCount: 11,
  ),
  SurahInfo(
    number: 64,
    englishName: 'At-Taghabun',
    arabicName: 'التغابن',
    revelationType: _d,
    ayahCount: 18,
  ),
  SurahInfo(
    number: 65,
    englishName: 'At-Talaq',
    arabicName: 'الطلاق',
    revelationType: _d,
    ayahCount: 12,
  ),
  SurahInfo(
    number: 66,
    englishName: 'At-Tahrim',
    arabicName: 'التحريم',
    revelationType: _d,
    ayahCount: 12,
  ),
  SurahInfo(
    number: 67,
    englishName: 'Al-Mulk',
    arabicName: 'الملك',
    revelationType: _m,
    ayahCount: 30,
  ),
  SurahInfo(
    number: 68,
    englishName: 'Al-Qalam',
    arabicName: 'القلم',
    revelationType: _m,
    ayahCount: 52,
  ),
  SurahInfo(
    number: 69,
    englishName: 'Al-Haqqah',
    arabicName: 'الحاقة',
    revelationType: _m,
    ayahCount: 52,
  ),
  SurahInfo(
    number: 70,
    englishName: "Al-Ma'arij",
    arabicName: 'المعارج',
    revelationType: _m,
    ayahCount: 44,
  ),
  SurahInfo(
    number: 71,
    englishName: 'Nuh',
    arabicName: 'نوح',
    revelationType: _m,
    ayahCount: 28,
  ),
  SurahInfo(
    number: 72,
    englishName: 'Al-Jinn',
    arabicName: 'الجن',
    revelationType: _m,
    ayahCount: 28,
  ),
  SurahInfo(
    number: 73,
    englishName: 'Al-Muzzammil',
    arabicName: 'المزمل',
    revelationType: _m,
    ayahCount: 20,
  ),
  SurahInfo(
    number: 74,
    englishName: 'Al-Muddaththir',
    arabicName: 'المدثر',
    revelationType: _m,
    ayahCount: 56,
  ),
  SurahInfo(
    number: 75,
    englishName: 'Al-Qiyamah',
    arabicName: 'القيامة',
    revelationType: _m,
    ayahCount: 40,
  ),
  SurahInfo(
    number: 76,
    englishName: 'Al-Insan',
    arabicName: 'الإنسان',
    revelationType: _d,
    ayahCount: 31,
  ),
  SurahInfo(
    number: 77,
    englishName: 'Al-Mursalat',
    arabicName: 'المرسلات',
    revelationType: _m,
    ayahCount: 50,
  ),
  SurahInfo(
    number: 78,
    englishName: 'An-Naba',
    arabicName: 'النبأ',
    revelationType: _m,
    ayahCount: 40,
  ),
  SurahInfo(
    number: 79,
    englishName: "An-Nazi'at",
    arabicName: 'النازعات',
    revelationType: _m,
    ayahCount: 46,
  ),
  SurahInfo(
    number: 80,
    englishName: 'Abasa',
    arabicName: 'عبس',
    revelationType: _m,
    ayahCount: 42,
  ),
  SurahInfo(
    number: 81,
    englishName: 'At-Takwir',
    arabicName: 'التكوير',
    revelationType: _m,
    ayahCount: 29,
  ),
  SurahInfo(
    number: 82,
    englishName: 'Al-Infitar',
    arabicName: 'الانفطار',
    revelationType: _m,
    ayahCount: 19,
  ),
  SurahInfo(
    number: 83,
    englishName: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    revelationType: _m,
    ayahCount: 36,
  ),
  SurahInfo(
    number: 84,
    englishName: 'Al-Inshiqaq',
    arabicName: 'الانشقاق',
    revelationType: _m,
    ayahCount: 25,
  ),
  SurahInfo(
    number: 85,
    englishName: 'Al-Buruj',
    arabicName: 'البروج',
    revelationType: _m,
    ayahCount: 22,
  ),
  SurahInfo(
    number: 86,
    englishName: 'At-Tariq',
    arabicName: 'الطارق',
    revelationType: _m,
    ayahCount: 17,
  ),
  SurahInfo(
    number: 87,
    englishName: "Al-A'la",
    arabicName: 'الأعلى',
    revelationType: _m,
    ayahCount: 19,
  ),
  SurahInfo(
    number: 88,
    englishName: 'Al-Ghashiyah',
    arabicName: 'الغاشية',
    revelationType: _m,
    ayahCount: 26,
  ),
  SurahInfo(
    number: 89,
    englishName: 'Al-Fajr',
    arabicName: 'الفجر',
    revelationType: _m,
    ayahCount: 30,
  ),
  SurahInfo(
    number: 90,
    englishName: 'Al-Balad',
    arabicName: 'البلد',
    revelationType: _m,
    ayahCount: 20,
  ),
  SurahInfo(
    number: 91,
    englishName: 'Ash-Shams',
    arabicName: 'الشمس',
    revelationType: _m,
    ayahCount: 15,
  ),
  SurahInfo(
    number: 92,
    englishName: 'Al-Layl',
    arabicName: 'الليل',
    revelationType: _m,
    ayahCount: 21,
  ),
  SurahInfo(
    number: 93,
    englishName: 'Ad-Duhaa',
    arabicName: 'الضحى',
    revelationType: _m,
    ayahCount: 11,
  ),
  SurahInfo(
    number: 94,
    englishName: 'Ash-Sharh',
    arabicName: 'الشرح',
    revelationType: _m,
    ayahCount: 8,
  ),
  SurahInfo(
    number: 95,
    englishName: 'At-Tin',
    arabicName: 'التين',
    revelationType: _m,
    ayahCount: 8,
  ),
  SurahInfo(
    number: 96,
    englishName: 'Al-Alaq',
    arabicName: 'العلق',
    revelationType: _m,
    ayahCount: 19,
  ),
  SurahInfo(
    number: 97,
    englishName: 'Al-Qadr',
    arabicName: 'القدر',
    revelationType: _m,
    ayahCount: 5,
  ),
  SurahInfo(
    number: 98,
    englishName: 'Al-Bayyinah',
    arabicName: 'البينة',
    revelationType: _d,
    ayahCount: 8,
  ),
  SurahInfo(
    number: 99,
    englishName: 'Az-Zalzalah',
    arabicName: 'الزلزلة',
    revelationType: _d,
    ayahCount: 8,
  ),
  SurahInfo(
    number: 100,
    englishName: 'Al-Adiyat',
    arabicName: 'العاديات',
    revelationType: _m,
    ayahCount: 11,
  ),
  SurahInfo(
    number: 101,
    englishName: "Al-Qari'ah",
    arabicName: 'القارعة',
    revelationType: _m,
    ayahCount: 11,
  ),
  SurahInfo(
    number: 102,
    englishName: 'At-Takathur',
    arabicName: 'التكاثر',
    revelationType: _m,
    ayahCount: 8,
  ),
  SurahInfo(
    number: 103,
    englishName: 'Al-Asr',
    arabicName: 'العصر',
    revelationType: _m,
    ayahCount: 3,
  ),
  SurahInfo(
    number: 104,
    englishName: 'Al-Humazah',
    arabicName: 'الهمزة',
    revelationType: _m,
    ayahCount: 9,
  ),
  SurahInfo(
    number: 105,
    englishName: 'Al-Fil',
    arabicName: 'الفيل',
    revelationType: _m,
    ayahCount: 5,
  ),
  SurahInfo(
    number: 106,
    englishName: 'Quraysh',
    arabicName: 'قريش',
    revelationType: _m,
    ayahCount: 4,
  ),
  SurahInfo(
    number: 107,
    englishName: "Al-Ma'un",
    arabicName: 'الماعون',
    revelationType: _m,
    ayahCount: 7,
  ),
  SurahInfo(
    number: 108,
    englishName: 'Al-Kawthar',
    arabicName: 'الكوثر',
    revelationType: _m,
    ayahCount: 3,
  ),
  SurahInfo(
    number: 109,
    englishName: 'Al-Kafirun',
    arabicName: 'الكافرون',
    revelationType: _m,
    ayahCount: 6,
  ),
  SurahInfo(
    number: 110,
    englishName: 'An-Nasr',
    arabicName: 'النصر',
    revelationType: _d,
    ayahCount: 3,
  ),
  SurahInfo(
    number: 111,
    englishName: 'Al-Masad',
    arabicName: 'المسد',
    revelationType: _m,
    ayahCount: 5,
  ),
  SurahInfo(
    number: 112,
    englishName: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    revelationType: _m,
    ayahCount: 4,
  ),
  SurahInfo(
    number: 113,
    englishName: 'Al-Falaq',
    arabicName: 'الفلق',
    revelationType: _m,
    ayahCount: 5,
  ),
  SurahInfo(
    number: 114,
    englishName: 'An-Nas',
    arabicName: 'الناس',
    revelationType: _m,
    ayahCount: 6,
  ),
];
